#!/usr/bin/env node
// Render one source of conventions + a generated skill index into every assistant's
// rule file: CLAUDE.md, AGENTS.md, .github/copilot-instructions.md, .cursor/rules/bow-skills.mdc.
//
// Zero dependencies. Run from a repo root:  node tooling/render-rules.mjs
//
// Each target keeps a managed block delimited by BOW:BEGIN / BOW:END — anything you write
// outside that block is preserved across re-runs. Edit tooling/conventions.base.md, not the
// generated files.

import { readFileSync, writeFileSync, existsSync, readdirSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';

const ROOT = process.cwd();
const BEGIN = '<!-- BOW:BEGIN — generated by tooling/render-rules.mjs. Edit tooling/conventions.base.md, not here. -->';
const END = '<!-- BOW:END -->';
const escapeRe = (s) => s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');

function readFrontmatter(file) {
  const src = readFileSync(file, 'utf8');
  if (!src.startsWith('---')) return {};
  const end = src.indexOf('\n---', 3);
  if (end === -1) return {};
  const fm = {};
  for (const line of src.slice(3, end).split('\n')) {
    const m = line.match(/^(\w+):\s*(.*)$/);
    if (m) fm[m[1]] = m[2].trim();
  }
  return fm;
}

function collectSkills() {
  const out = [];
  const pluginsDir = join(ROOT, 'plugins');
  if (!existsSync(pluginsDir)) return out;
  for (const plugin of readdirSync(pluginsDir)) {
    const skillsDir = join(pluginsDir, plugin, 'skills');
    if (!existsSync(skillsDir)) continue;
    for (const skill of readdirSync(skillsDir)) {
      const f = join(skillsDir, skill, 'SKILL.md');
      if (!existsSync(f)) continue;
      const fm = readFrontmatter(f);
      if (fm.name) out.push({ plugin, name: fm.name, description: fm.description || '' });
    }
  }
  return out.sort((a, b) => a.plugin.localeCompare(b.plugin) || a.name.localeCompare(b.name));
}

const firstSentence = (s) => {
  const m = s.match(/^(.*?\.)(\s|$)/);
  return (m ? m[1] : s).trim();
};

function buildBody() {
  const base = readFileSync(join(ROOT, 'tooling', 'conventions.base.md'), 'utf8').trim();
  const skills = collectSkills();
  let index =
    '\n\n## Skill index\n\n' +
    'When a task matches one of these, follow that workflow. In Claude Code the full skill loads ' +
    'automatically; in other assistants, treat this as the index and apply the named process.\n\n' +
    '| Skill | Plugin | Use when |\n|---|---|---|\n';
  for (const s of skills) index += `| \`${s.name}\` | ${s.plugin} | ${firstSentence(s.description)} |\n`;
  return base + index;
}

function writeManaged(file, body, { frontmatter } = {}) {
  mkdirSync(dirname(file), { recursive: true });
  const block = `${BEGIN}\n${body}\n${END}`;
  const existing = existsSync(file) ? readFileSync(file, 'utf8') : '';
  let next;
  if (existing.includes(BEGIN) && existing.includes(END)) {
    next = existing.replace(new RegExp(escapeRe(BEGIN) + '[\\s\\S]*?' + escapeRe(END)), block);
  } else {
    next = (frontmatter ? frontmatter + '\n' : '') + block + (existing ? '\n\n' + existing.trimStart() : '\n');
  }
  writeFileSync(file, next);
  console.log('wrote', file.replace(ROOT + '/', ''));
}

const body = buildBody();
writeManaged(join(ROOT, 'CLAUDE.md'), body);
writeManaged(join(ROOT, 'AGENTS.md'), body);
writeManaged(join(ROOT, '.github', 'copilot-instructions.md'), body);
writeManaged(join(ROOT, '.cursor', 'rules', 'bow-skills.mdc'), body, {
  frontmatter: '---\ndescription: BOW Skills engineering conventions\nalwaysApply: true\n---',
});
console.log('done — edit tooling/conventions.base.md and re-run to regenerate.');
